//This file is generated by tools!
//Please do not modify this file!
public class DataDefine {

	public const int CommonProperty_CommonProperty_property_name = 0;
	public const int CommonProperty_CommonProperty_property_value = 1;
	public const int CommonProperty_CommonProperty_F3 = 2;
	public const int CommonProperty_CommonProperty_F4 = 3;

}