//This file is generated by tools
//Please do not modify this file
public class TText{
public const int SUCCESS = 0;
public const int LOGIN_PASSWORD_WRONG = 1;
public const int ERROR_NOT_FOUND = 2;
public const int ERROR_1102_1 = 3;
public const int ERROR_1102_2 = 4;
}
